# .github/workflows/publish.yml

name: Publish Package to npmjs # Name of the workflow

on: # Event that triggers the workflow
  push:
    # tags:
    #   - 'v*'
    branches:
      - master
# Jobs that run in the workflow
jobs:
  # build job
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm i -D husky@^9.1.6
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
